social_distribution/nodes/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from nodes import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'social_distribution.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'test/$', views.test, name='test'),
    )

social_distribution/social_distribution/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'social_distribution.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('posts.urls')),
    url('', include('authors.urls')),
    url('', include('nodes.urls'))
)

social_distribution/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from authors.models import Profile
import uuid

# Create your models here.

class Post(models.Model):
    PRIVACY_CHOICES = (('1', 'Public'),
                      ('2', 'Private'),
                      ('3','Friend of a Friend'),
                      ('4','Friends on this Server'),
                      ('5','Friends'))

    CONTENT_TYPE_CHOICES = (('text/plain', 'Plain text'),
                            ('text/x-markdown', 'Markdown'),
                            ('text/html', 'HTML'))

    uuid = models.CharField(max_length=36, default = uuid.uuid4)
    title = models.CharField(max_length=128, blank=True)
    description = models.CharField(max_length=512, blank=True)
    content_type = models.CharField(max_length=32, choices=CONTENT_TYPE_CHOICES)
    post_text = models.TextField(max_length=2048)
    image = models.ImageField(upload_to='post_images', blank=True)
    author = models.ForeignKey(Profile)
    date = models.DateTimeField('date posted')
    privacy = models.CharField(max_length=1, choices=PRIVACY_CHOICES)
    allowed=models.ManyToManyField(Profile,null=True,blank=True, related_name="allowed")

    def get_image_path(self):
        return self.image.path
    def __unicode__(self):
        return str(self.author)

class Comment(models.Model):
    post_id = models.ForeignKey(Post)
    uuid = models.CharField(max_length=36, default = uuid.uuid4)
    body = models.TextField(max_length=2048)
    author = models.ForeignKey(Profile)
    date = models.DateTimeField('date posted')

    def __unicode__(self):
        return str(self.author)

social_distribution/templates/github_template.html
{% if my_profile.github and list_of_github %}
{% for event in list_of_github %}
    <div class="panel panel-info align">
        <div class="panel-heading">
            <h4 class="panel-title">{{ event.title|safe|escape }}</h4>
        </div>
        <div class="panel-body">
            <h5>
                <p class="text-muted">
                    {{ event.post_text }}
                </p>
            </h5>
        </div>
        <br/>
    </div>
{% endfor %}
{% elif not my_profile.github %}
    <div>
        <h2>
            You haven't linked a <a href="http://www.github.com">Github</a>
            account yet! Set one <a href="/manage">here</a>!
        </h2>
    </div>
{% elif not list_of_github %}
    <div>
        <h2>
            There is no activity to display for this Github account!
        </h2>
    </div>
{% endif %}

social_distribution/templates/post_template.html
{% for post in list_of_posts %}
    {% if post.author.host = 'http://cs410.cs.ualberta.ca:41024' %}
        <div class="panel panel-info">
    {% else %}
        <div class="panel panel-warning">
    {% endif %}
        <div class="panel-heading">
            <h1 class="panel-title"> {{post.title}}</h1>
        </div>
        <div class="panel-body align">
            <p>Post by {{post.author}} on {{post.date}}</p>
            <p>{{post.post_text|safe|escape}}</p>
            <br/>

            {% if post.image %}
                <div>
                    <img src="{{MEDIA_URL}}{{post.uuid}}" alt="{{post.image}}" height="100" width="100"/>
                </div>
            {% endif %}
                <p>This post's privacy is {{post.get_privacy_display}}</p>
            {% if post.author.user = user %}
                <br/>
                <div class="button-container">
                    <form id="expand_post" method="get" action="/posts/{{post.uuid}}/">
                        <input class="btn btn-success btn-sm" type="submit" value="Expand" />
                    </form>
                    <form id="edit_post" method="get" action="/edit/post/{{post.uuid}}">
                        <input class="btn btn-warning btn-sm" type="submit" value="Edit" />
                    </form>
                    <form id="delete_post" method="post" action="/delete/post/{{post.uuid}}">
                        {% csrf_token %}
                        <input class="btn btn-danger btn-sm" type="submit" value="Delete" />
                    </form>
                </div>


            {% else %}
                <br/>
                <div>
                    <form id="expand_post" method="get" action="/posts/{{post.uuid}}/">
                        <input class="btn btn-success btn-sm" type="submit" value="Expand" />
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endfor %}